### ISSUE TITLE
docker build for libpcre3 fails

### ISSUE THREAD

**Issue by imenyoo2** [Nautilus-Institute/quals-2024#1]
command: `sudo docker build -tag libpcre .`

failure error:
```
touch configure-stamp
dh_testdir
# Add here commands to compile the package.
./makevp_c.txt -j2
make: ./makevp_c.txt: Permission denied
make: *** [debian/rules:54: build-stamp] Error 127
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
The command '/bin/sh -c if [ -f ./build.sh ]; then ./build.sh; fi' returned a non-zero code: 2
```
 any idea why this happens ?

**Comment by itszn** [comment]
It seems like somehow the initial find command is locating the incorrect file on your device.

`MAKE=$(shell find $(DEB_BUILD_ROOT) -type f | grep /make | head -n1)` should locate `makevp.bat` instead of `makevp_c.txt`
```
$ cd pcre3-8.39
$ find $(DEB_BUILD_ROOT) -type f | grep /make | head -n1
DEB_BUILD_ROOT: command not found
./makevp.bat
```

I personally have not hit this failure on any devices I tested on (including most importantly the CI which was the "target" of the backdoor builder) but maybe your FS is returning an unexpected ordering?

You can probably throw a `| sort` into the find command to fix the issue I would imagine
